set(TORQUE_APPLE_TARGET "" CACHE STRING "The apple target")
set_property(CACHE TORQUE_APPLE_TARGET PROPERTY STRINGS macOS iphoneOS)

set(TORQUE_APPLE_IOS_PLATFORM "" CACHE STRING "The iOS platform")
set_property(CACHE TORQUE_IOS_PLATFORM PROPERTY STRINGS OS SIMULATOR)

if("${TORQUE_APPLE_TARGET}" STREQUAL "")
	message(FATAL_ERROR "Please set TORQUE_APPLE_TARGET and if iOS set TORQUE_APPLE_IOS_PLATFORM platform.")
endif()

if(${TORQUE_APPLE_IOS_PLATFORM} STREQUAL "iphoneOS")
set(IOS TRUE)
endif()