name: Windows Test Results
on:
  workflow_run:
    workflows: ["Windows Build"]
    types:
      - completed

permissions:
    checks: write

jobs:
    checks:
        name: ${{matrix.config.name}}
        runs-on: ${{matrix.config.runos}}
        strategy:
            fail-fast: false
            matrix:
              config: 
              - {
                  name: "Windows Test Results",
                  runos: windows-latest,
                  artifact-name: "torque3dWindowsMSVCUnitTest"
                }

        steps:
            - name: Download Windows Test Report
              uses: dawidd6/action-download-artifact@v3
              with:
                path: Windows
                name: ${{matrix.config.artifact-name}}
                workflow: ${{ github.event.workflow.id }}
                run_id: ${{ github.event.workflow_run.id }}

            - name: Test Reporter
              uses: phoenix-actions/test-reporting@v14
              with:
                name: ${{matrix.config.name}}
                path: Windows/*.xml
                reporter: java-junit
