name: Linux Test Results
on:
  workflow_run:
    workflows: ["Linux Build"]
    types:
      - completed

permissions:
    checks: write

jobs:
    checks:
        name: ${{matrix.config.name}}
        runs-on: ${{matrix.config.runos}}
        strategy:
            fail-fast: false
            matrix:
              config: 
              - {
                  name: "Linux Test Results",
                  runos: ubuntu-latest,
                  artifact-name: "torque3dLinuxGCCUnitTest"
                }
              
        steps:
            - name: Download Linux Test Report
              uses: dawidd6/action-download-artifact@v3
              with:
                path: Linux
                name: ${{matrix.config.artifact-name}}
                workflow: ${{ github.event.workflow.id }}
                run_id: ${{ github.event.workflow_run.id }}

            - name: Test Reporter
              uses: phoenix-actions/test-reporting@v14
              with:
                name: ${{matrix.config.name}}
                path: "**/My Projects/Torque3D/game/test_detail.xml"
                reporter: java-junit
